# calls tools/ci_build/get_docker_image.py

parameters:
- name: Dockerfile
  type: string
- name: Context
  type: string
- name: DockerBuildArgs
  type: string
  default: ""
- name: Repository
  type: string
- name: UseImageCacheContainerRegistry
  type: boolean
  default: true
- name: ScriptName
  type: string
  default: "tools/ci_build/get_docker_image.py" 
- name: UpdateDepsTxt
  type: boolean
  default: true
  
steps:
- ${{ if and(eq(parameters.UpdateDepsTxt, true), eq(variables['System.CollectionId'], 'f3ad12f2-e480-4533-baf2-635c95467d29')) }}:
  - task: DownloadPackage@1
    displayName: 'Download ONNX Runtime Build Time Deps'
    inputs:
      packageType: upack
      feed: '/7424c8e4-5c62-490e-95c4-79446f31017c'
      definition: '517c4f6f-5437-4392-a70d-4f15ec5be2f0'
      version: 1.0.0
      downloadPath: $(Build.BinariesDirectory)/deps
      
- ${{ if and(eq(parameters.UpdateDepsTxt, true), eq(variables['System.CollectionId'], 'bc038106-a83b-4dab-9dd3-5a41bc58f34c')) }}:
  - task: DownloadPackage@1
    displayName: 'Download ONNX Runtime Build Time Deps'
    inputs:
      packageType: upack
      feed: '/4c7631f5-24c0-4307-8822-1aa8f180c325'
      definition: 'fd9dd5ad-b73e-4678-890e-edcf680dbc1a'
      version: 1.0.0
      downloadPath: $(Build.BinariesDirectory)/deps

- ${{ if contains(parameters.Dockerfile, 'manylinux') }}:
    - checkout: manylinux
    - script: |
        set -e -x 
        mv manylinux onnxruntime
        mv onnxruntime ..
        cd ..
        rmdir $(Build.SourcesDirectory)
        mv onnxruntime $(Build.SourcesDirectory)
      displayName: "Move Manylinux source code to ORT folder"

- ${{ if eq(parameters.UseImageCacheContainerRegistry, true) }}:
  - template: with-container-registry-steps.yml
    parameters:
      Steps:
      - script: |
          ${{ parameters.ScriptName }} \
            --dockerfile "${{ parameters.Dockerfile }}" \
            --context "${{ parameters.Context }}" \
            --docker-build-args "${{ parameters.DockerBuildArgs }}" \
            --container-registry onnxruntimebuildcache \
            --repository "${{ parameters.Repository }}"
        displayName: "Get ${{ parameters.Repository }} image for ${{ parameters.Dockerfile }}"
      ContainerRegistry: onnxruntimebuildcache
- ${{ if eq(parameters.UseImageCacheContainerRegistry, false) }}:
  - script: |
      ${{ parameters.ScriptName }} \
        --dockerfile "${{ parameters.Dockerfile }}" \
        --context "${{ parameters.Context }}" \
        --docker-build-args "${{ parameters.DockerBuildArgs }}" \
        --repository "${{ parameters.Repository }}"
    displayName: "Get ${{ parameters.Repository }} image for ${{ parameters.Dockerfile }}"

- ${{ if and(eq(parameters.UpdateDepsTxt, true), or(eq(variables['System.CollectionId'], 'f3ad12f2-e480-4533-baf2-635c95467d29'),eq(variables['System.CollectionId'], 'bc038106-a83b-4dab-9dd3-5a41bc58f34c'))) }}:
  - task: PythonScript@0
    displayName: 'Update deps.txt'
    inputs:
      scriptPath: $(Build.SourcesDirectory)/tools/ci_build/replace_urls_in_deps.py
      arguments: --new_dir /build/deps
      workingDirectory: $(Build.BinariesDirectory)
      pythonInterpreter: /usr/bin/python3